### ISSUE TITLE
MultiPurposePopupViewController Deinit 호출 안됨 외 1

### ISSUE THREAD

**Issue by KangTaeHoon** [billboardoo/WaktaverseMusic-iOS-UIKit#103]
### 할 일

1. MultiPurposePopupViewController dismiss시 deinit이 호출되도록 수정

2. MultiPurposePopupViewModel 에서 
flatMap > map으로 수정 

![image](https://user-images.githubusercontent.com/37323252/220533779-8d5727e4-3bcc-4fa9-8229-1c935e2110a5.png)

**Comment by yongbeomkwak** [comment]
수정했습니다
