### ISSUE TITLE
This method should not be called on the main thread as it may lead to UI unresponsiveness.

### ISSUE THREAD

**Issue by KangTaeHoon** [billboardoo/WaktaverseMusic-iOS-UIKit#104]
### 할 일

![image](https://user-images.githubusercontent.com/37323252/220542427-428fefd6-7301-4dcc-8808-a29be661bcb2.png)

youtube 동영상 재생 이후 계속 뜬다.. 뭐야이건...

**Comment by yongbeomkwak** [comment]
신경을 안써도 된다는건가요?? 아니면 .. 패키지 자체 깔려있는 버그라는 뜻인가요?

**Comment by youn9k** [comment]
> 신경을 안써도 된다는건가요?? 아니면 .. 패키지 자체 깔려있는 버그라는 뜻인가요?

https://developer.apple.com/forums/thread/714467
여기 보시면 애플쪽 버그란 이야기가 많아요
