### ISSUE TITLE
드래그 앤 드랍 애니메이션 및 영역 고정

### ISSUE THREAD

**Issue by yongbeomkwak** [billboardoo/WaktaverseMusic-iOS-UIKit#112]
https://user-images.githubusercontent.com/48616183/221358678-b986b335-b3b2-41ed-b881-feea6d2fd9b7.mov

**Comment by KangTaeHoon** [comment]
1차 처리 완료되었고, 다른화면 까지 수정되면 닫아주세요. @yongbeomkwak
