### ISSUE TITLE
동영상 재생 시 경고문구

### ISSUE THREAD

**Issue by youn9k** [billboardoo/WaktaverseMusic-iOS-UIKit#119]
### 설명

<img width="524" alt="image" src="https://user-images.githubusercontent.com/60254939/223002315-9e2cf67f-42da-41ca-951b-3a07d6055e1a.png">

동영상을 재생시키면 플레이에는 문제가 없으나 위같은 경고문구가 너무 많이뜸..

### 같은 고민중인 스레드들 링크
https://github.com/youtube/youtube-ios-player-helper/issues/443
https://developer.apple.com/forums/thread/709919

유튜브플레이어킷은 내부적으로 wkwebview 를 사용하고 있는데, ~~iOS 15 이상에서 wkwebview 를 사용하면 해당 문구가 뜨는듯하다.~~
iPhone8 iOS 14.0.1 에서도 경고문구 확인

**Comment by KangTaeHoon** [comment]
웹뷰 사용하면 특히 저러는걸 많이 봤었는데,, 저는 무시했습니다.
