### ISSUE TITLE
편집 모드 진입 시 플레이 버튼 잔상 남아 있습니다.

### ISSUE THREAD

**Issue by yongbeomkwak** [billboardoo/WaktaverseMusic-iOS-UIKit#151]
### 설명

<img width="314" alt="스크린샷 2023-03-25 오후 2 04 00" src="https://user-images.githubusercontent.com/48616183/227697370-ad7d61be-6cd6-4c11-ab4b-4d9d8bf3fbae.png">

**Comment by KangTaeHoon** [comment]
⚡️ :: 플리상세, 내 리스트, 좋아요 편집모드 진입 시 애니메이션 제거 

이슈 닫습니다.
