### ISSUE TITLE
검색 결과에서 프로맥스에서 글자가 짤려서 나와요

### ISSUE THREAD

**Issue by kimdaehee0824** [billboardoo/WaktaverseMusic-iOS-UIKit#155]
### 설명

전체보기 라는 라벨이 잘려 있습니다

![IMG_4435](https://user-images.githubusercontent.com/68860610/227723572-95eb160a-8453-4c0e-a035-8d0939e1a17c.png)

**Comment by yongbeomkwak** [comment]
이슈 감사합니다
