### ISSUE TITLE
플레이어 곡, 아티스트명 길때 흐르는 효과

### ISSUE THREAD

**Issue by youn9k** [billboardoo/WaktaverseMusic-iOS-UIKit#159]
### 할 일

https://github.com/cbpowell/MarqueeLabel
위 라이브러리 적용하면될듯

**Comment by KangTaeHoon** [comment]
그대로 따라하시면 됩니다.  테스트 결과 잘 작동합니다.

1. Dependency+SPM.swift, Dependencies.swift에 추가

<img width="1749" alt="스크린샷 2023-04-09 오후 11 37 39" src="https://user-images.githubusercontent.com/37323252/230779205-8ce30b5a-e4ad-46e7-a285-9f61a4146b47.png">


2. ThirdPartyLib/Project.swift, FeatureThirdPartyLib/swift에 추가 
extension에 속성을 정의할 수도 있으니 두 군데 다 추가해줍시다.

![스크린샷 2023-04-09 오후 11 37 45](https://user-images.githubusercontent.com/37323252/230779252-59e45db1-9558-4272-8a81-9c1897a5c072.png)

3. 사용할 곳의 UILabel() 클래스를 MarqueeLabel()로 바꾸고 속성을 정의합니다. 

![스크린샷 2023-04-09 오후 11 34 28](https://user-images.githubusercontent.com/37323252/230779291-39f0b18d-d3cf-459c-baaf-6752ce92dc3d.png)

4. 결과

https://user-images.githubusercontent.com/37323252/230779359-71dd1a4f-c3f6-4720-83b5-7a1cffe28725.mp4

**Comment by youn9k** [comment]
@KangTaeHoon 결과동영상에선 안움직이는데 동영상문제라면 푸시하고 이슈 닫아주시면 감사하겠습니다👍
