### ISSUE TITLE
실기기에서 네이버 로그인 안되는 버그

### ISSUE THREAD

**Issue by youn9k** [billboardoo/WaktaverseMusic-iOS-UIKit#161]
### 설명

콘솔에도 아무것도 안찍히네요 흠흠

https://user-images.githubusercontent.com/60254939/228255115-63f559f0-d967-4d8c-b3e5-f16753be9346.mov

<img width="615" alt="image" src="https://user-images.githubusercontent.com/60254939/228256654-0ba16b04-2509-4a88-93f8-06f7ad4061b3.png">

**Comment by KangTaeHoon** [comment]
해결해서 닫습니다
