### ISSUE TITLE
삭제된 노래(?) 안나오는 노래(?) 예외처리

### ISSUE THREAD

**Issue by KangTaeHoon** [billboardoo/WaktaverseMusic-iOS-UIKit#180]
### 설명

<img width="1785" alt="스크린샷 2023-04-02 오후 3 49 06" src="https://user-images.githubusercontent.com/37323252/229337296-00d83551-49fa-4f76-a319-2e97ce7ac2fb.png">

주르르 - SigSig 보면 썸네일을 못불러와서 기본이미지로 들어가있는데, 

재생을 하면 스샷 처럼 되고 노래는 나오지않음. (재생 중이라는 로티이미지는 돌아가는 상태)

프로그래스바는 이전에 재생중이던 곡의 상태로 적용되어있고 작동하지 않음.

1. '가사가 없습니다.' 메세지를 '재생할 수 없는 곡입니다.' 정도로 바꾼다.

2. 프로그래스바도 0:00으로 초기화 (이전에 재생하던 곡의 프로그래스가 그대로 남아있음)

3. 기본이미지를 넣어준다. 

현재는 버그 처럼 보임.

**Comment by youn9k** [comment]
비공개로 돌린 영상인 경우로 확인
