### ISSUE TITLE
앱 사용 권한 안내

### ISSUE THREAD

**Issue by yongbeomkwak** [billboardoo/WaktaverseMusic-iOS-UIKit#182]
### 할 일

- 앱 최초 설치 후 접속 시 사용 권한 팝업으로 안내(최초 1회)

### 추가사항
- 앱 스토어 설명 최하단에 추가 

왁타버스 뮤직에서 사용하는 접근권한 안내
[필수]: 없음
[선택]: 카메라, 앨범
선택권한은 서비스 사용 중 필요한 시점에 동의를 받고 있습니다. 허용하지 않으셔도 서비스 이용이 가능합니다.

_No response_

**Comment by KangTaeHoon** [comment]
@yongbeomkwak 앱 내 권한 팝업 작업은 끝났으니, 앱 스토어 앱 설명 란에 적어주시고 이슈 닫아주세요.

**Comment by yongbeomkwak** [comment]
추가 완료
