### ISSUE TITLE
다음 곡 재생 시 화면에 보이지 않는 셀이면 애니메이션이 동작안하는 문제

### ISSUE THREAD

**Issue by youn9k** [billboardoo/WaktaverseMusic-iOS-UIKit#202]
### 설명

https://user-images.githubusercontent.com/60254939/230761923-3eb020a2-08b1-4351-8b05-c79f6a370298.mov

```Swift
private func bindwaveStreamAnimationView(output: PlaylistViewModel.Output) {
        output.playerState
            .compactMap { [weak self] state -> (PlaylistTableViewCell, Bool)? in
                guard let self else { return nil }
                let index = self.playState.playList.currentPlayIndex
               // 안보이는 셀은 찾을 수 없음
                guard let cell = self.playlistView.playlistTableView.cellForRow(at: IndexPath(row: index, section: 0)) as? PlaylistTableViewCell else { return nil }
                return (cell, state == .playing)
            }
            .sink { cell, isAnimating in
                if isAnimating {
                    cell.waveStreamAnimationView.play()
                } else {
                    cell.waveStreamAnimationView.pause()
                }
            }
            .store(in: &subscription)
    }
```

**Comment by youn9k** [comment]
currentPlayIndex 를 따로 변수로 제어하는것 자체가 버그를 일으킬 가능성이 너무 큼. 
PlayState.PlayList의 요소에 재생중 여부를 같이 저장해야할듯

**Comment by KangTaeHoon** [comment]
아시다시피 셀은 재사용 되는 특성때문에 화면에 보일때마다 테이블 뷰의 데이터소스가 정의된 부분이 계속 불립니다. 그곳에서 재생버튼이 보일지 로티 애니메이션이 보일지 결정하는 값을 셀에다가 계속 주입 시켜줘야합니다. 그래야 원하는 동작이 나올겁니다. 

테이블 뷰로부터 n번째 셀을 찾아내서 업데이트하는건 셀이 화면에 있을때만 가능합니다. 이런 로직은 다 지우세요. 반쪽 짜리 기능입니다.

**Comment by youn9k** [comment]
> 아시다시피 셀은 재사용 되는 특성때문에 화면에 보일때마다 테이블 뷰의 데이터소스가 정의된 부분이 계속 불립니다. 그곳에서 재생버튼이 보일지 로티 애니메이션이 보일지 결정하는 값을 셀에다가 계속 주입 시켜줘야합니다. 그래야 원하는 동작이 나올겁니다. 
> 
> 테이블 뷰로부터 n번째 셀을 찾아내서 업데이트하는건 셀이 화면에 있을때만 가능합니다. 이런 로직은 다 지우세요. 반쪽 짜리 기능입니다.

감사합니다! 안그래도 지금 playlist클래스랑 관련로직 뜯어고치는중이었습니다😂
