### ISSUE TITLE
곡 재생 후 플레이어 전체모드로 전환시 앱 크래시

### ISSUE THREAD

**Issue by youn9k** [billboardoo/WaktaverseMusic-iOS-UIKit#208]
### 설명

곡 재생 후 너무 빨리 플레이어를 누르면 가사가 불러오기전이라 그런지 앱이 죽음
<img width="1075" alt="Pasted Graphic 1" src="https://user-images.githubusercontent.com/60254939/231694996-5df05bf1-902c-4705-8428-248a6dc38302.png">

**Comment by KangTaeHoon** [comment]
오류 내용만 보면 가사 테이블 뷰가 완전히 로드되기 전에 해당 로우에 접근한걸로 보이네요.
