### ISSUE TITLE
검색 후 페이지 탭 고정되는 버그

### ISSUE THREAD

**Issue by yongbeomkwak** [billboardoo/WaktaverseMusic-iOS-UIKit#24]
### 설명

검색 후 , 탭을 노래, 가수 ,조교로 이동 시킨 후 , 검색을 지우고 , 다시 검색해 들어올 때, 전체 탭이 아닌 이전 탭을 그대로 바라보고 있음

**Comment by KangTaeHoon** [comment]
검색이 실행 될 때, 

TabmanViewController를 상속하고있는 VC에서         

let targetIndex: Int = 0
self.scrollToPage(.at(index: targetIndex), animated: false)

위의 로직을 실행해주면 될 것 같습니다.

**Comment by KangTaeHoon** [comment]
override func viewWillAppear(_ animated: Bool) {
        super.viewWillAppear(animated)
        
        //VC가 add 될때 해당 라이프사이클이 매번 호출되므로 여기가 적합해 보입니다. 테스트 해보시기 바랍니다.
        // viewDidAppear는 사용자 눈에 보이므로 자연스럽지가 않습니다.
    }
