### ISSUE TITLE
[중요] 메모리 누수: [weak self] 반드시 체크 할 것

### ISSUE THREAD

**Issue by KangTaeHoon** [billboardoo/WaktaverseMusic-iOS-UIKit#74]
### 할 일

Push, Modal로 이동되었다가 다시 사라지는 화면은 반드시 

deinit { DEBUG_LOG("\(Self.self) deinit") }

구문을 찍어두시고 deinit 로그가 찍히는지 확인 하시기바랍니다.

안 찍히면 메모리 해제가 안된 것입니다.

**Comment by yongbeomkwak** [comment]
현재 플레이 리스트 디테일 제외 모든 공통팝업 소멸자 호출 확인 
1. 프로필 팝업
2. 텍스트 팝업
3. 다용도 팝업 (키보드 입력 받는 팝업)
4. PDF 뷰컨
5. 플레이리스트 디테일 ( 통과 ❌)
