### ISSUE TITLE
닉네임 최대 설정 8글자로 변경

### ISSUE THREAD

**Issue by KangTaeHoon** [billboardoo/WaktaverseMusic-iOS-UIKit#75]
### 할 일

닉네임 최대 설정 8글자로 변경합니다.

1. 닉네임 설정 화면에서의 limit 8로 수정

2. 로그아웃 버튼의 우측 제약조건 설정 (>= 10): 어떠한 경우에도 화면 밖으로 넘어 갈 수 없도록 미리 방지

3. Extension+String에 추가

    /// WM 규칙에 맞게 닉네임을 보정 합니다. (최대 글자 수: 8)
    var correctionNickName: String {
        let limit: Int = 8
        return self.count > limit ? String(self.prefix(limit)) + "..." : self
    }
    
    : 최초 회원 가입 시 SNS 계정에 설정 된  닉네임이 8글자보다 많게 설정된 경우 때문에 예외 처리 용입니다.
      8글자보다 넘어가면 8자리까지만 가져온 후, + "..."을 붙여 보여줍니다.

**Comment by yongbeomkwak** [comment]
모두 반영했습니다 :)
