### ISSUE TITLE
jwt 플러그인 만들기

### ISSUE THREAD

**Issue by kimdaehee0824** [billboardoo/WaktaverseMusic-iOS-UIKit#94]
### 할 일

jwt 플러그인 만들기

**Comment by KangTaeHoon** [comment]
public var jwtTokenType: JwtTokenType {
    return .accessToken
}

**API에 jwtTokenType 리턴 값만 .accessToken으로 바꿔주면 잘 되는것으로 확인했습니다.  코드봐도 구현되어 있는 것으로 보이는데요..?

----------------------------------------
API: setProfile(image: "gorani")
header: [
"Content-Type": "application/json", 
"Authorization": "Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjAwMTA5OS5kYjUxYmZiZGI3MjM0YTdiYjE0ZmY5ZmYzYTk2MzQ0My4wOTIxIiwiaWF0IjoxNjc2NzMzOTcwLCJleHAiOjE2NzczMzg3NzB9.dJ460cEXGXrZrKE0QSLeE4pcHzIYPWO4MDkKromyrBs"
]
{"image":"gorani"}

**Comment by kimdaehee0824** [comment]
헉 넣어놨나 보네요 이슈는 닫겠습니다
